name: Build and Release

on:
  push:
    branches:
      - "**"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next tag version
        id: next_tag
        run: |
          latest_tag=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            next_tag="v0.0.5"
          else
            IFS='.' read -r major minor patch <<< "${latest_tag#v}"
            patch=$((patch+1))
            next_tag="v$major.$minor.$patch"
          fi
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT

      - name: Build binary
        run: |
          make

      - name: Create new tag
        run: |
          git config user.name "frosthaern"
          git config user.email "shashankbharadwaj0001@gmail.com"
          git tag ${{ steps.next_tag.outputs.next_tag }}
          git push https://x-access-token:${{ secrets.TASKTREE }}@github.com/${{ github.repository }} ${{ steps.next_tag.outputs.next_tag }}

      - name: Rename binary for release
        run: |
          cp tasktree tasktree-${{ steps.next_tag.outputs.next_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_tag.outputs.next_tag }}
          name: Release ${{ steps.next_tag.outputs.next_tag }}
          files: |
            tasktree-${{ steps.next_tag.outputs.next_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.TASKTREE }}
